### ISSUE TITLE
Test generation for empty class failed

### ISSUE THREAD

**Issue by operasfantom** [UnitTestBot/unittestbot.github.io#24]
### Describe the bug

Test generation for empty class failed. The output is as follows:

```
Status Code: TEST_GENERATION_FAILED

TEST GENERATION: TEST_GENERATION_FAILED
12:06:16.568 | INFO  | AllInMemoryClassProvider | Loaded: 3 path entries, 19922 classes, 62288191 bytes
12:06:17.733 | ERROR | GenerateTestsCommand | An error has occurred while generating test for snippet Solution : java.util.NoSuchElementException: List is empty.
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:212)
	at org.utbot.cli.GenerateTestsCommand.run(GenerateTestsCommand.kt:98)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:204)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:213)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436)
	at org.utbot.cli.ApplicationKt.main(Application.kt:31)

TEST RUN: ERROR OCCURRED
[object Object]: no details
```

### Steps to reproduce

1. Visit utbot.org
2. Choose Java as a language
4. Generate and run tests for given empty class

### Expected behavior

Meaningful log message

### Reproduction link

Doesn't work

### Screenshots

![image](https://user-images.githubusercontent.com/31903947/171851059-95292330-26f8-44c4-8624-291312e4f48c.png)

**Comment by victoriafomina** [comment]
Closed due to being fixed. Meaningful log message for the current situation was added.
